import type {
  BadgeRfid,
  Borne,
  Facture,
  KpisClient,
  SessionRecharge,
  Utilisateur,
  Vehicule,
} from '@/types/domain';

/**
 * Données de démonstration utilisées tant que l'API Laravel n'est pas branchée
 * (voir lib/api.ts — USE_MOCK).
 */

export const mockUtilisateur: Utilisateur = {
  id: 1,
  nom: 'Rzeigui',
  prenom: 'Maram',
  email: 'rzprodtn@gmail.com',
  telephone: '+216 20 000 000',
  role: 'client',
  soldeWallet: 45.5,
};

export const mockBornes: Borne[] = [
  {
    id: 1,
    source: 'reseau',
    operateur: null,
    nom: 'Borne Lac 1',
    reference: 'BRN-TUN-001',
    numeroSerie: 'SN-88412-A',
    modele: 'Terra AC W22',
    fabricant: 'ABB',
    adresse: 'Rue du Lac Turkana, Les Berges du Lac, Tunis',
    latitude: 36.8324,
    longitude: 10.2331,
    versionFirmware: '1.8.2',
    versionOcpp: '1.6',
    puissanceKw: 22,
    etat: 'disponible',
    dernierHeartbeat: new Date(Date.now() - 30_000).toISOString(),
    temperatureC: 31,
    tarifKwh: 0.45,
    connecteurs: [
      { id: 1, borneId: 1, type: 'Type2', puissanceKw: 22, etat: 'disponible' },
      { id: 2, borneId: 1, type: 'Type2', puissanceKw: 22, etat: 'disponible' },
    ],
  },
  {
    id: 2,
    source: 'reseau',
    operateur: null,
    nom: 'Borne Centre Urbain Nord',
    reference: 'BRN-TUN-002',
    numeroSerie: 'SN-88413-B',
    modele: 'Supernova 60',
    fabricant: 'Wallbox',
    adresse: 'Centre Urbain Nord, Tunis',
    latitude: 36.8508,
    longitude: 10.1897,
    versionFirmware: '2.1.0',
    versionOcpp: '2.0.1',
    puissanceKw: 60,
    etat: 'occupee',
    dernierHeartbeat: new Date(Date.now() - 12_000).toISOString(),
    temperatureC: 38,
    tarifKwh: 0.62,
    connecteurs: [
      { id: 3, borneId: 2, type: 'CCS', puissanceKw: 60, etat: 'occupe' },
      { id: 4, borneId: 2, type: 'CHAdeMO', puissanceKw: 50, etat: 'disponible' },
    ],
  },
  {
    id: 3,
    source: 'reseau',
    operateur: null,
    nom: 'Borne La Marsa Plage',
    reference: 'BRN-TUN-003',
    numeroSerie: 'SN-88414-C',
    modele: 'Terra 54',
    fabricant: 'ABB',
    adresse: 'Avenue Habib Bourguiba, La Marsa',
    latitude: 36.8781,
    longitude: 10.3247,
    versionFirmware: '1.7.9',
    versionOcpp: '1.6',
    puissanceKw: 50,
    etat: 'maintenance',
    dernierHeartbeat: new Date(Date.now() - 3_600_000).toISOString(),
    temperatureC: 29,
    tarifKwh: 0.58,
    connecteurs: [
      { id: 5, borneId: 3, type: 'CCS', puissanceKw: 50, etat: 'indisponible' },
      { id: 6, borneId: 3, type: 'Type2', puissanceKw: 22, etat: 'indisponible' },
    ],
  },
  {
    id: 4,
    source: 'reseau',
    operateur: null,
    nom: 'Borne Sousse Corniche',
    reference: 'BRN-SOU-001',
    numeroSerie: 'SN-91201-A',
    modele: 'EVBox Troniq 100',
    fabricant: 'EVBox',
    adresse: 'Boulevard de la Corniche, Sousse',
    latitude: 35.8256,
    longitude: 10.6084,
    versionFirmware: '3.0.1',
    versionOcpp: '2.0.1',
    puissanceKw: 100,
    etat: 'disponible',
    dernierHeartbeat: new Date(Date.now() - 45_000).toISOString(),
    temperatureC: 33,
    tarifKwh: 0.7,
    connecteurs: [
      { id: 7, borneId: 4, type: 'CCS', puissanceKw: 100, etat: 'disponible' },
      { id: 8, borneId: 4, type: 'CHAdeMO', puissanceKw: 62, etat: 'disponible' },
    ],
  },
  {
    id: 5,
    source: 'reseau',
    operateur: null,
    nom: 'Borne Sfax Centre',
    reference: 'BRN-SFX-001',
    numeroSerie: 'SN-91355-D',
    modele: 'Terra AC W7',
    fabricant: 'ABB',
    adresse: 'Avenue Hédi Chaker, Sfax',
    latitude: 34.7406,
    longitude: 10.7603,
    versionFirmware: '1.8.2',
    versionOcpp: '1.6',
    puissanceKw: 7,
    etat: 'deconnectee',
    dernierHeartbeat: new Date(Date.now() - 86_400_000).toISOString(),
    tarifKwh: 0.4,
    connecteurs: [{ id: 9, borneId: 5, type: 'AC', puissanceKw: 7, etat: 'indisponible' }],
  },
];

export const mockSessionActive: SessionRecharge = {
  id: 100,
  borneId: 2,
  borneNom: 'Borne Centre Urbain Nord',
  connecteurId: 3,
  typeConnecteur: 'CCS',
  vehiculeId: 1,
  dateDebut: new Date(Date.now() - 25 * 60_000).toISOString(),
  energieKwh: 18.4,
  prix: 11.41,
  etat: 'en_cours',
  puissanceInstantaneeKw: 52.3,
  pourcentageBatterie: 64,
};

export const mockSessions: SessionRecharge[] = [
  mockSessionActive,
  {
    id: 99,
    borneId: 1,
    borneNom: 'Borne Lac 1',
    connecteurId: 1,
    typeConnecteur: 'Type2',
    vehiculeId: 1,
    dateDebut: '2026-08-28T09:12:00Z',
    dateFin: '2026-08-28T10:47:00Z',
    dureeMinutes: 95,
    energieKwh: 31.2,
    prix: 14.04,
    etat: 'terminee',
  },
  {
    id: 98,
    borneId: 4,
    borneNom: 'Borne Sousse Corniche',
    connecteurId: 7,
    typeConnecteur: 'CCS',
    vehiculeId: 1,
    dateDebut: '2026-08-21T14:05:00Z',
    dateFin: '2026-08-21T14:38:00Z',
    dureeMinutes: 33,
    energieKwh: 42.7,
    prix: 29.89,
    etat: 'terminee',
  },
  {
    id: 97,
    borneId: 1,
    borneNom: 'Borne Lac 1',
    connecteurId: 2,
    typeConnecteur: 'Type2',
    vehiculeId: 1,
    dateDebut: '2026-08-14T18:30:00Z',
    dateFin: '2026-08-14T18:41:00Z',
    dureeMinutes: 11,
    energieKwh: 3.1,
    prix: 1.4,
    etat: 'annulee',
  },
];

export const mockVehicules: Vehicule[] = [
  {
    id: 1,
    marque: 'Renault',
    modele: 'Mégane E-Tech',
    immatriculation: '220 TU 4521',
    typeConnecteur: 'CCS',
    capaciteBatterieKwh: 60,
  },
];

export const mockBadges: BadgeRfid[] = [
  { id: 1, uid: 'A4:5F:22:9C', actif: true, dateExpiration: '2027-01-01' },
];

export const mockFactures: Facture[] = [
  { id: 1, sessionId: 99, numero: 'FAC-2026-0099', date: '2026-08-28', montantTtc: 14.04 },
  { id: 2, sessionId: 98, numero: 'FAC-2026-0098', date: '2026-08-21', montantTtc: 29.89 },
];

export const mockKpis: KpisClient = {
  sessionsTotal: 24,
  energieTotaleKwh: 612.8,
  depensesTotal: 348.2,
  dureeMoyenneMinutes: 47,
  parMois: [
    { mois: '2026-04', kwh: 88, prix: 51.2, sessions: 3 },
    { mois: '2026-05', kwh: 104, prix: 60.1, sessions: 4 },
    { mois: '2026-06', kwh: 72, prix: 41.8, sessions: 3 },
    { mois: '2026-07', kwh: 131, prix: 76.4, sessions: 5 },
    { mois: '2026-08', kwh: 118, prix: 68.3, sessions: 5 },
    { mois: '2026-09', kwh: 99, prix: 50.4, sessions: 4 },
  ],
  kmAjoutes: 3605,
  kwhAux100Km: 17,
};
